### ISSUE TITLE
Can't using ru lang.

### ISSUE THREAD

**Issue by DiBel-v** [denisotree/hyphenated-ru#1]
I installed both hyphenated from 'hyphenated' and ru from 'hyphenated-ru', but when I try to get formatted text, I get what was originally.
It works with en lang, but not with ru.
let txt = hyphenated(txt, { lagnuage: ru });
console.log(txt.replace(/\u00AD/g, '~'));
This code returns the same as original text without '~'.
What am I doing wrong?

**Comment by denisotree** [comment]
Hey!
You need to create HyphenopolyText component
```
import Hyphenated from 'react-hyphen';
import ru from 'hyphenated-ru';

const HyphenopolyText = props => (
        props.lang === "ru" ?
            <Hyphenated language={ru}>
                {props.text}
            </Hyphenated>
            :
            <Hyphenated>
                {props.text}
            </Hyphenated>
);

export default HyphenopolyText
```
Then use it in your project
```
import HyphenoplyText from '../HyphenopolyText';
...
<div className="foo-text">

<HyphenoplyText
lang={this.props.current_lang}
text={this.props[`text_${this.props.current_lang}`]}
/>

</div>
...
```
Like here, for example
